/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'

const AboutLazyRouteImport = createFileRoute('/about')()
const AuthenticatedExpensesLazyRouteImport = createFileRoute(
  '/_authenticated/expenses',
)()
const AuthenticatedCreateExpenseLazyRouteImport = createFileRoute(
  '/_authenticated/create-expense',
)()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesLazyRoute =
  AuthenticatedExpensesLazyRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/expenses.lazy').then((d) => d.Route),
  )
const AuthenticatedCreateExpenseLazyRoute =
  AuthenticatedCreateExpenseLazyRouteImport.update({
    id: '/create-expense',
    path: '/create-expense',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/create-expense.lazy').then((d) => d.Route),
  )
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutLazyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/create-expense': typeof AuthenticatedCreateExpenseLazyRoute
  '/expenses': typeof AuthenticatedExpensesLazyRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/create-expense': typeof AuthenticatedCreateExpenseLazyRoute
  '/expenses': typeof AuthenticatedExpensesLazyRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/create-expense': typeof AuthenticatedCreateExpenseLazyRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/profile' | '/create-expense' | '/expenses' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/profile' | '/create-expense' | '/expenses' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/profile'
    | '/_authenticated/create-expense'
    | '/_authenticated/expenses'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-expense': {
      id: '/_authenticated/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof AuthenticatedCreateExpenseLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCreateExpenseLazyRoute: typeof AuthenticatedCreateExpenseLazyRoute
  AuthenticatedExpensesLazyRoute: typeof AuthenticatedExpensesLazyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCreateExpenseLazyRoute: AuthenticatedCreateExpenseLazyRoute,
  AuthenticatedExpensesLazyRoute: AuthenticatedExpensesLazyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
